version: '3'

services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: docker
    volumes: 
      - ./docker/postgres/volumes:/var/lib/postgresql/data

  uwsgi:
    build:
      context: .
      dockerfile: ./docker/django-app/Dockerfile
    environment:
      BANK_MODE: docker-prod
    volumes:
      - ./docker/django-app/uwsgi.ini:/usr/src/django-app/main/uwsgi.ini:ro
      - ./docker/socket:/usr/src/django-app/socket
      - ./docker/django-app/logs:/usr/src/django-app/logs
    depends_on:
      - db
    entrypoint: uwsgi --ini /usr/src/django-app/main/uwsgi.ini

  nginx:
    image: nginx
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./django-app/main/uwsgi_params:/usr/share/nginx/uwsgi_params:ro
      - ./django-app/static:/usr/share/nginx/static
      - ./django-app/media:/usr/share/nginx/media
      - ./docker/socket:/usr/share/nginx/socket
    ports:
      - 80:8080
    depends_on:
      - uwsgi
      - db