app:
  build: .
  #image: python
  volumes:
    - .:/usr/src/app
    - ../coolfig/coolfig:/usr/local/lib/python2.7/site-packages/coolfig
    - .pip-cache:/var/cache/pip
  environment:
    - PYTHONPATH=.
  env_file: .env
  entrypoint: ./_cmd.py

devpi:
  image: python:2.7.9
  volumes:
    - .pip-cache:/usr/src/app
  working_dir: /usr/src/app
  command: python -m SimpleHTTPServer 8000
  ports:
    - 80:8000

deps:
  build: deps
  volumes:
    - .:/usr/src/app
    - .pip-cache:/var/cache/pip
  working_dir: /usr/src/app
  command: pip wheel --find-links=/var/cache/pip --wheel-dir=/var/cache/pip --no-deps -r requirements.txt
