appName: tulo_bot
logLevel: WARN

DEV:
  mongodb:
    url: mongodb://127.0.0.1:27017/tulo_bot
    db: tulo_bot
  namespace:
    dns: http://127.0.0.1:5000/
  df_columns:
    col_lang: lang
    col_category: category
    col_query: query
    col_variables: variables
    col_response: response
    col_input_circumstance: input_circumstance
    col_output_circumstance: output_circumstance
  flatfile:
    location: modules/data/
    mongo_train_fileName: train.csv
  cache:
    redis_url: redis://127.0.0.1:6379
    redis_host: 127.0.0.1
    redis_user: ""
    redis_port: 6379
    redis_password: ""
    ttl: 180
    max_size: 10000
  model:
    file:
      location: modules/saved_models/
      response_classifier: CLASSIFIER_TFIDF_LOGISTIC_RESPONSE_01.sav
    classifier:
      model: LOGISTIC
    vectorizer:
      vector: TFIDF
  auth:
    telegram:
      token: 911971525:AAExau9c1NCnZMeFOZ-xEvkOyNmwtgJJbA8

PROD:
  mongodb:
    url: mongodb://heroku_2r6cnrs1:os02s46gjpp2b0mio9qa4o3g8g@ds229078.mlab.com:29078/heroku_2r6cnrs1?retryWrites=false
    db: heroku_2r6cnrs1
  namespace:
    dns: https://bankbot-app.herokuapp.com
  df_columns:
    col_lang: lang
    col_category: category
    col_query: query
    col_variables: variables
    col_response: response
    col_input_circumstance: input_circumstance
    col_output_circumstance: output_circumstance
  flatfile:
    location: modules/data/
    mongo_train_fileName: train.csv
  cache:
    redis_url: redis://h:p5c7f90b9d1b59e8b344f56c66fd89ad90bfc02e55d181f53386f01a096c7bed7@ec2-3-225-205-83.compute-1.amazonaws.com:18209
    redis_host: ec2-3-225-205-83.compute-1.amazonaws.com
    redis_user: h
    redis_port: 18209
    redis_password: p5c7f90b9d1b59e8b344f56c66fd89ad90bfc02e55d181f53386f01a096c7bed7
    ttl: 180
    max_size: 10000
  model:
    file:
      location: modules/saved_models/
      response_classifier: CLASSIFIER_TFIDF_LOGISTIC_RESPONSE_01.sav
    classifier:
      model: LOGISTIC
    vectorizer:
      vector: TFIDF
  auth:
    telegram:
      token: 911971525:AAExau9c1NCnZMeFOZ-xEvkOyNmwtgJJbA8